from gym_multigrid.envs.soccer_game import SoccerGame4HEnv10x15N2
from gym_multigrid.envs.collect_game import CollectGame3Obj2Agent
from gym_multigrid.envs.collect_game import CollectGame3ObjFixed2Agent
from gym_multigrid.envs.collect_game import CollectGame3ObjSingleAgent
from gym_multigrid.envs.wildfire import WildfireEnv
